targets:
  $default:
    builders:
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/src/application/router/application_router.dart
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/src/application/widget/screen/**.dart
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'
      json_serializable:
        enabled: true
        generate_for:
          - lib/**.dart
        options:
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true