arb-dir: lib/src/application/l10n
template-arb-file: en.arb
output-localization-file: application_localization.dart
output-class: ApplicationLocalization
nullable-getter: false
untranslated-messages-file: lib/src/application/l10n/untranslated.txt