arb-dir: lib/src/presentation/l10n
template-arb-file: en.arb
output-localization-file: application_localization.dart
output-class: ApplicationLocalization
nullable-getter: false
untranslated-messages-file: untranslated.txt