name: multivendor_clean_architecture_starter
description: Multivendor starter repository for new project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  # Framework
  flutter:
    sdk: flutter
  # Application
  auto_route:
  bloc_concurrency:
  mvs_widget:
    path: package/mvs_widget
  flutter_bloc:
  flutter_localizations:
    sdk: flutter
  flutter_platform_component:
  intl:
  # Data
  dio:
  drift:
  sqlite3_flutter_libs:
  mvs_rest:
    path: package/mvs_rest
  json_annotation:
  # Utility
  collection:
  equatable:
  l:
  mvs_utility:
    path: package/mvs_utility
  path:
  path_provider:
  stack_trace:
  flutter_launcher_icons:
  flutter_native_splash:
  url_strategy:


dev_dependencies:
  # Application
  auto_route_generator:
  # Data
  drift_dev:
  json_serializable:
  # Test
  flutter_test:
    sdk: flutter
  test:
  # Utility
  build_runner:
  flutter_lints:

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: IconData
      fonts:
        - asset: asset/font/IconData.ttf
  assets:
    - asset/vec/