name: multi_vendor_starter
description: Multivendor starter repo for new project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  flutter_lints:
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  
flutter_localizations:
  sdk: flutter

# Don't change this for correct environment script work
flutter_launcher_icons:
  image_path: asset/application_icon/application_icon.png
  ios: true
  remove_alpha_ios: true
  android: launcher_icon
  min_sdk_android: 21

# Don't change this for correct environment script work
flutter_native_splash:
  color: "#000000"
  color_dark: "#111111"
  background_image: "asset/application_splash/background_splash.png"
  background_image_dark: "asset/application_splash/background_splash_dark.png"
  image: "asset/application_splash/application_splash.png"
  image_dark: "asset/application_splash/application_splash_dark.png"
  ios: true
  android: true
  android_12:
    color: "#000000"
    color_dark: "#111111"
    icon_background_color: "#000000"
    icon_background_color_dark: "#111111"
    image: "asset/application_splash/application_splash_android_12.png"
    image_dark: "asset/application_splash/application_splash_android_12_dark.png"