name: multi_vendor_starter
description: Multivendor starter repo for new project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  # Framework
  flutter:
    sdk: flutter

  # Data
  dio:
  freezed_annotation:
  json_annotation:

  # Presentation
  auto_route:
  flutter_bloc:
  flutter_localizations:
    sdk: flutter
  flutter_platform_component:
  intl:

  # Utility
  l:
  stack_trace:
  flutter_launcher_icons:
  flutter_native_splash:
  url_strategy:

dev_dependencies:
  # Test
  flutter_test:
    sdk: flutter
  test:

  # Data
  freezed:
  json_serializable:

  # Presentation
  auto_route_generator:

  # Utility
  build_runner:
  flutter_lints:

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: IconData
      fonts:
        - asset: asset/font/IconData.ttf
  assets:
    - asset/vec/