name: mvs_utility
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  l: ^4.0.2
  plugin_platform_interface: ^2.0.2
  stack_trace: ^1.11.1
  url_strategy: ^0.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
