name: mvs_rest
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.6

dependencies:
  dio: ^5.4.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner:
  json_serializable:
  lints: ^2.1.0
  test: ^1.24.0
